name: Deploy PR previews

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
    paths:
      - 'docs/**'
      - '**.md'
      - '**.html'

concurrency: preview-${{ github.ref }}

jobs:
  deploy-preview:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # - name: Install and Build
      #   run: |
      #     npm install
      #     npm run build

      - name: Deploy PR Preview
        uses: rossjrw/pr-preview-action@v1.1.1

        with:
          preview-branch: main
